export const INIT_PRODUCTS_LIST = 'INIT_PRODUCTS_LIST';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const INIT_CURRENT_PRODUCT_CARD = 'INIT_CURRENT_PRODUCT_CARD';
