export const INIT_PRODUCTS_LIST = 'INIT_PRODUCTS_LIST';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const INIT_CURRENT_PRODUCT_CARD = 'INIT_CURRENT_PRODUCT_CARD';
<<<<<<< HEAD
export const UPDATE_PRODUCT_IN_STOK = 'UPDATE_PRODUCT_IN_STOK';

=======
export const CHANGE_PRODUCT_STATUS = 'CHANGE_PRODUCT_STATUS';
>>>>>>> 1fc043e16ed8dca3d7d63b9524405e5f80764b6b
