export const ADD_PRODUCT_BASKET = 'ADD_PRODUCT_BASKET';
export const  UPDATE_PRODUCT_BASKET = 'UPDATE_PRODUCT_BASKET';
export const  DELETE_PRODUCT_BASKET = 'DELETE_PRODUCT_BASKET';
export const  CLEAR_BASKET = 'CLEAR_BASKET';
